// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → activities*
 */
export interface AboutDocumentDataActivitiesItem {
  /**
   * activity field in *About → activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.activities[].activity
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  activity: prismic.KeyTextField;
}

type AboutDocumentDataSlicesSlice =
  | SkillsSlice
  | AboutSlice
  | BigImageSlice
  | CatchphraseSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * born field in *About*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: about.born
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  born: prismic.DateField;

  /**
   * city field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * activities field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.activities[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  activities: prismic.GroupField<Simplify<AboutDocumentDataActivitiesItem>>;

  /**
   * image cover field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image_cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_cover: prismic.ImageField<never>;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Contact → skills*
 */
export interface ContactDocumentDataSkillsItem {
  /**
   * skill field in *Contact → skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.skills[].skill
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skill: prismic.KeyTextField;
}

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * mail field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.mail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * catchphrase field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.catchphrase
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  catchphrase: prismic.KeyTextField;

  /**
   * skills field in *Contact*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.skills[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<ContactDocumentDataSkillsItem>>;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Footer → socials*
 */
export interface FooterDocumentDataSocialsItem {
  /**
   * social field in *Footer → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].social
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * city field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * mail field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.mail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * socials field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = AllProjectsSlice | NameSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PhotoDocumentDataSlicesSlice = HeroSlice | PhotoSlice;

/**
 * Content for Photo documents
 */
interface PhotoDocumentData {
  /**
   * Slice Zone field in *Photo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PhotoDocumentDataSlicesSlice> /**
   * Meta Title field in *Photo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: photo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Photo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: photo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Photo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Photo document from Prismic
 *
 * - **API ID**: `photo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PhotoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PhotoDocumentData>, "photo", Lang>;

/**
 * Item in *Project → Main categories*
 */
export interface ProjectDocumentDataMainCategoriesItem {
  /**
   * main category field in *Project → Main categories*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project.main_categories[].main_category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  main_category: prismic.SelectField<"Design" | "Web" | "Video" | "Misc.">;
}

/**
 * Item in *Project → Categories*
 */
export interface ProjectDocumentDataCategoriesItem {
  /**
   * Category field in *Project → Categories*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project.categories[].category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Art Direction"
    | "Branding & Identity"
    | "Typography"
    | "Web Design"
    | "Print Design"
    | "Web Development"
    | "Video Direction"
    | "Web development"
    | "Editing"
    | "Experimental"
  >;
}

/**
 * Item in *Project → collaborators*
 */
export interface ProjectDocumentDataCollaboratorsItem {
  /**
   * name field in *Project → collaborators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.collaborators[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

type ProjectDocumentDataSlicesSlice =
  | AboutSlice
  | BigImageSlice
  | CatchphraseSlice
  | ProjectContentSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Name field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Date field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Main categories field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.main_categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main_categories: prismic.GroupField<
    Simplify<ProjectDocumentDataMainCategoriesItem>
  >;

  /**
   * Categories field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  categories: prismic.GroupField<Simplify<ProjectDocumentDataCategoriesItem>>;

  /**
   * Image Main field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.image_main
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_main: prismic.ImageField<never>;

  /**
   * View more field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.view_more
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  view_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * favorite field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.favorite
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  favorite: prismic.BooleanField;

  /**
   * collaborators field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.collaborators[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  collaborators: prismic.GroupField<
    Simplify<ProjectDocumentDataCollaboratorsItem>
  >;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | ContactDocument
  | FooterDocument
  | HomepageDocument
  | PhotoDocument
  | ProjectDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * about field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *AllProjects → Default → Primary*
 */
export interface AllProjectsSliceDefaultPrimary {
  /**
   * Project field in *AllProjects → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: all_projects.default.primary.project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;

  /**
   * image field in *AllProjects → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: all_projects.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AllProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AllProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AllProjects*
 */
type AllProjectsSliceVariation = AllProjectsSliceDefault;

/**
 * AllProjects Shared Slice
 *
 * - **API ID**: `all_projects`
 * - **Description**: AllProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllProjectsSlice = prismic.SharedSlice<
  "all_projects",
  AllProjectsSliceVariation
>;

/**
 * Primary content in *BigImage → Default → Primary*
 */
export interface BigImageSliceDefaultPrimary {
  /**
   * image field in *BigImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BigImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BigImage*
 */
type BigImageSliceVariation = BigImageSliceDefault;

/**
 * BigImage Shared Slice
 *
 * - **API ID**: `big_image`
 * - **Description**: BigImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigImageSlice = prismic.SharedSlice<
  "big_image",
  BigImageSliceVariation
>;

/**
 * Primary content in *Catchphrase → Default → Primary*
 */
export interface CatchphraseSliceDefaultPrimary {
  /**
   * catchphrase field in *Catchphrase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catchphrase.default.primary.catchphrase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  catchphrase: prismic.KeyTextField;
}

/**
 * Default variation for Catchphrase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchphraseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatchphraseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Catchphrase*
 */
type CatchphraseSliceVariation = CatchphraseSliceDefault;

/**
 * Catchphrase Shared Slice
 *
 * - **API ID**: `catchphrase`
 * - **Description**: Catchphrase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchphraseSlice = prismic.SharedSlice<
  "catchphrase",
  CatchphraseSliceVariation
>;

/**
 * Item in *Contact → Default → Primary → socials*
 */
export interface ContactSliceDefaultPrimarySocialsItem {
  /**
   * icon field in *Contact → Default → Primary → socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.socials[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * social field in *Contact → Default → Primary → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.socials[].social
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * city field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.city
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * mail field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.mail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mail: prismic.KeyTextField;

  /**
   * socials field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<ContactSliceDefaultPrimarySocialsItem>>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * image mobile field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * image desktop field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Name → Default → Primary*
 */
export interface NameSliceDefaultPrimary {
  /**
   * image mobile field in *Name → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: name.default.primary.image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * image desktop field in *Name → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: name.default.primary.image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;
}

/**
 * Default variation for Name Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NameSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NameSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Name*
 */
type NameSliceVariation = NameSliceDefault;

/**
 * Name Shared Slice
 *
 * - **API ID**: `name`
 * - **Description**: Name
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NameSlice = prismic.SharedSlice<"name", NameSliceVariation>;

/**
 * Primary content in *NextProject → Default → Primary*
 */
export interface NextProjectSliceDefaultPrimary {
  /**
   * nextproject field in *NextProject → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: next_project.default.primary.nextproject
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nextproject: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for NextProject Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NextProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NextProject*
 */
type NextProjectSliceVariation = NextProjectSliceDefault;

/**
 * NextProject Shared Slice
 *
 * - **API ID**: `next_project`
 * - **Description**: NextProject
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextProjectSlice = prismic.SharedSlice<
  "next_project",
  NextProjectSliceVariation
>;

/**
 * Item in *Photo → Default → Primary → onePhoto*
 */
export interface PhotoSliceDefaultPrimaryOnephotoItem {
  /**
   * name field in *Photo → Default → Primary → onePhoto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.default.primary.onephoto[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * date field in *Photo → Default → Primary → onePhoto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.default.primary.onephoto[].date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * photo field in *Photo → Default → Primary → onePhoto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.default.primary.onephoto[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * album field in *Photo → Default → Primary → onePhoto*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.default.primary.onephoto[].album
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  album: prismic.SelectField<
    | "Lights night"
    | "Espace muséal"
    | "Summer thoughts"
    | "Jump!"
    | "Canada"
    | "Subway"
  >;
}

/**
 * Primary content in *Photo → Default → Primary*
 */
export interface PhotoSliceDefaultPrimary {
  /**
   * onePhoto field in *Photo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.default.primary.onephoto[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  onephoto: prismic.GroupField<Simplify<PhotoSliceDefaultPrimaryOnephotoItem>>;
}

/**
 * Default variation for Photo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhotoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Photo*
 */
type PhotoSliceVariation = PhotoSliceDefault;

/**
 * Photo Shared Slice
 *
 * - **API ID**: `photo`
 * - **Description**: Photo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoSlice = prismic.SharedSlice<"photo", PhotoSliceVariation>;

/**
 * Primary content in *ImageSlide → Default → Primary*
 */
export interface ProjectContentSliceDefaultPrimary {
  /**
   * Image_vertical field in *ImageSlide → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_content.default.primary.image_vertical
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_vertical: prismic.ImageField<never>;

  /**
   * Image_horizontal field in *ImageSlide → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_content.default.primary.image_horizontal
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_horizontal: prismic.ImageField<never>;
}

/**
 * Default variation for ImageSlide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageSlide → VideoSlide → Primary*
 */
export interface ProjectContentSliceVideoSlidePrimary {
  /**
   * Image_vertical field in *ImageSlide → VideoSlide → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_content.videoSlide.primary.image_vertical
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_vertical: prismic.ImageField<never>;

  /**
   * video field in *ImageSlide → VideoSlide → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_content.videoSlide.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * VideoSlide variation for ImageSlide Slice
 *
 * - **API ID**: `videoSlide`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectContentSliceVideoSlide = prismic.SharedSliceVariation<
  "videoSlide",
  Simplify<ProjectContentSliceVideoSlidePrimary>,
  never
>;

/**
 * Slice variation for *ImageSlide*
 */
type ProjectContentSliceVariation =
  | ProjectContentSliceDefault
  | ProjectContentSliceVideoSlide;

/**
 * ImageSlide Shared Slice
 *
 * - **API ID**: `project_content`
 * - **Description**: ProjectContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectContentSlice = prismic.SharedSlice<
  "project_content",
  ProjectContentSliceVariation
>;

/**
 * Item in *Skills → Default → Primary → abilities*
 */
export interface SkillsSliceDefaultPrimaryAbilitiesItem {
  /**
   * name field in *Skills → Default → Primary → abilities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.abilities[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Item in *Skills → Default → Primary → technologies*
 */
export interface SkillsSliceDefaultPrimaryTechnologiesItem {
  /**
   * name field in *Skills → Default → Primary → technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.technologies[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Item in *Skills → Default → Primary → softwares*
 */
export interface SkillsSliceDefaultPrimarySoftwaresItem {
  /**
   * name field in *Skills → Default → Primary → softwares*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.softwares[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * image field in *Skills → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * abilities field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.abilities[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  abilities: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimaryAbilitiesItem>
  >;

  /**
   * technologies field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.technologies[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  technologies: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimaryTechnologiesItem>
  >;

  /**
   * softwares field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.softwares[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  softwares: prismic.GroupField<
    Simplify<SkillsSliceDefaultPrimarySoftwaresItem>
  >;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

/**
 * Item in *Works → Default → Primary → Works*
 */
export interface WorksSliceDefaultPrimaryWorksItem {
  /**
   * name field in *Works → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.works[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * image field in *Works → Default → Primary → Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.works[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Works → Default → Primary*
 */
export interface WorksSliceDefaultPrimary {
  /**
   * Works field in *Works → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.works[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  works: prismic.GroupField<Simplify<WorksSliceDefaultPrimaryWorksItem>>;
}

/**
 * Default variation for Works Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Works*
 */
type WorksSliceVariation = WorksSliceDefault;

/**
 * Works Shared Slice
 *
 * - **API ID**: `works`
 * - **Description**: Works
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSlice = prismic.SharedSlice<"works", WorksSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataActivitiesItem,
      AboutDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSkillsItem,
      ContactDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialsItem,
      FooterDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PhotoDocument,
      PhotoDocumentData,
      PhotoDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataMainCategoriesItem,
      ProjectDocumentDataCategoriesItem,
      ProjectDocumentDataCollaboratorsItem,
      ProjectDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AllProjectsSlice,
      AllProjectsSliceDefaultPrimary,
      AllProjectsSliceVariation,
      AllProjectsSliceDefault,
      BigImageSlice,
      BigImageSliceDefaultPrimary,
      BigImageSliceVariation,
      BigImageSliceDefault,
      CatchphraseSlice,
      CatchphraseSliceDefaultPrimary,
      CatchphraseSliceVariation,
      CatchphraseSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimarySocialsItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      NameSlice,
      NameSliceDefaultPrimary,
      NameSliceVariation,
      NameSliceDefault,
      NextProjectSlice,
      NextProjectSliceDefaultPrimary,
      NextProjectSliceVariation,
      NextProjectSliceDefault,
      PhotoSlice,
      PhotoSliceDefaultPrimaryOnephotoItem,
      PhotoSliceDefaultPrimary,
      PhotoSliceVariation,
      PhotoSliceDefault,
      ProjectContentSlice,
      ProjectContentSliceDefaultPrimary,
      ProjectContentSliceVideoSlidePrimary,
      ProjectContentSliceVariation,
      ProjectContentSliceDefault,
      ProjectContentSliceVideoSlide,
      SkillsSlice,
      SkillsSliceDefaultPrimaryAbilitiesItem,
      SkillsSliceDefaultPrimaryTechnologiesItem,
      SkillsSliceDefaultPrimarySoftwaresItem,
      SkillsSliceDefaultPrimary,
      SkillsSliceVariation,
      SkillsSliceDefault,
      WorksSlice,
      WorksSliceDefaultPrimaryWorksItem,
      WorksSliceDefaultPrimary,
      WorksSliceVariation,
      WorksSliceDefault,
    };
  }
}
