// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DesignDocumentDataSlicesSlice =
  | NextProjectSlice
  | CatchphraseSlice
  | CreditsSlice
  | ComplementSlice
  | BigImageSlice;

/**
 * Content for Design documents
 */
interface DesignDocumentData {
  /**
   * name field in *Design*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: design.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * year field in *Design*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: design.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * category field in *Design*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: design.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * image presentation field in *Design*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: design.image_presentation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_presentation: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Design*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: design.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DesignDocumentDataSlicesSlice> /**
   * Meta Title field in *Design*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: design.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Design*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: design.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Design*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: design.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Design document from Prismic
 *
 * - **API ID**: `design`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DesignDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DesignDocumentData>, "design", Lang>;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PhotoDocumentDataSlicesSlice = never;

/**
 * Content for Photo documents
 */
interface PhotoDocumentData {
  /**
   * Slice Zone field in *Photo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PhotoDocumentDataSlicesSlice> /**
   * Meta Title field in *Photo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: photo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Photo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: photo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Photo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Photo document from Prismic
 *
 * - **API ID**: `photo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PhotoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PhotoDocumentData>, "photo", Lang>;

type VideoDocumentDataSlicesSlice =
  | CreditsSlice
  | BigImageSlice
  | CatchphraseSlice
  | ComplementSlice;

/**
 * Content for Video documents
 */
interface VideoDocumentData {
  /**
   * name field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * year field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * category field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * image_presentation field in *Video*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.image_presentation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_presentation: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Video*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: video.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VideoDocumentDataSlicesSlice> /**
   * Meta Title field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: video.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: video.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Video*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<VideoDocumentData>, "video", Lang>;

type WebDocumentDataSlicesSlice =
  | CreditsSlice
  | ComplementSlice
  | CatchphraseSlice
  | BigImageSlice;

/**
 * Content for Web documents
 */
interface WebDocumentData {
  /**
   * name field in *Web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * category field in *Web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * year field in *Web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * image presentation field in *Web*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: web.image_presentation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_presentation: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Web*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: web.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WebDocumentDataSlicesSlice> /**
   * Meta Title field in *Web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: web.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Web*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: web.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Web*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: web.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Web document from Prismic
 *
 * - **API ID**: `web`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WebDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WebDocumentData>, "web", Lang>;

type WorksDocumentDataSlicesSlice = WorksSlice;

/**
 * Content for works documents
 */
interface WorksDocumentData {
  /**
   * Slice Zone field in *works*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: works.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorksDocumentDataSlicesSlice>;
}

/**
 * works document from Prismic
 *
 * - **API ID**: `works`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<WorksDocumentData>, "works", Lang>;

export type AllDocumentTypes =
  | DesignDocument
  | PageDocument
  | PhotoDocument
  | VideoDocument
  | WebDocument
  | WorksDocument;

/**
 * Primary content in *BigImage → Default → Primary*
 */
export interface BigImageSliceDefaultPrimary {
  /**
   * imgBig field in *BigImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_image.default.primary.imgbig
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imgbig: prismic.ImageField<never>;
}

/**
 * Default variation for BigImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BigImage → video → Primary*
 */
export interface BigImageSliceVideoPrimary {
  /**
   * video field in *BigImage → video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: big_image.video.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;
}

/**
 * video variation for BigImage Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigImageSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<BigImageSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *BigImage*
 */
type BigImageSliceVariation = BigImageSliceDefault | BigImageSliceVideo;

/**
 * BigImage Shared Slice
 *
 * - **API ID**: `big_image`
 * - **Description**: BigImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BigImageSlice = prismic.SharedSlice<
  "big_image",
  BigImageSliceVariation
>;

/**
 * Primary content in *Catchphrase → Default → Primary*
 */
export interface CatchphraseSliceDefaultPrimary {
  /**
   * catchphrase field in *Catchphrase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: catchphrase.default.primary.catchphrase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  catchphrase: prismic.KeyTextField;
}

/**
 * Default variation for Catchphrase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchphraseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatchphraseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Catchphrase*
 */
type CatchphraseSliceVariation = CatchphraseSliceDefault;

/**
 * Catchphrase Shared Slice
 *
 * - **API ID**: `catchphrase`
 * - **Description**: Catchphrase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatchphraseSlice = prismic.SharedSlice<
  "catchphrase",
  CatchphraseSliceVariation
>;

/**
 * Primary content in *Complement → Default → Primary*
 */
export interface ComplementSliceDefaultPrimary {
  /**
   * about field in *Complement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: complement.default.primary.about
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about: prismic.KeyTextField;

  /**
   * img 1 field in *Complement → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: complement.default.primary.img_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img_1: prismic.ImageField<never>;

  /**
   * img 2 field in *Complement → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: complement.default.primary.img_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img_2: prismic.ImageField<never>;
}

/**
 * Default variation for Complement Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComplementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComplementSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Complement → video → Primary*
 */
export interface ComplementSliceVideoPrimary {
  /**
   * about field in *Complement → video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: complement.video.primary.about
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about: prismic.KeyTextField;

  /**
   * img 1 field in *Complement → video → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: complement.video.primary.img_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img_1: prismic.ImageField<never>;

  /**
   * video field in *Complement → video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: complement.video.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * video variation for Complement Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComplementSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<ComplementSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *Complement*
 */
type ComplementSliceVariation = ComplementSliceDefault | ComplementSliceVideo;

/**
 * Complement Shared Slice
 *
 * - **API ID**: `complement`
 * - **Description**: Complement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComplementSlice = prismic.SharedSlice<
  "complement",
  ComplementSliceVariation
>;

/**
 * Item in *Credits → Default → Primary → Client*
 */
export interface CreditsSliceDefaultPrimaryClientItem {
  /**
   * content field in *Credits → Default → Primary → Client*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.client[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Item in *Credits → Default → Primary → Year*
 */
export interface CreditsSliceDefaultPrimaryYearItem {
  /**
   * year field in *Credits → Default → Primary → Year*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.year[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;
}

/**
 * Item in *Credits → Default → Primary → role*
 */
export interface CreditsSliceDefaultPrimaryRoleItem {
  /**
   * role field in *Credits → Default → Primary → role*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.role[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;
}

/**
 * Item in *Credits → Default → Primary → Softwares*
 */
export interface CreditsSliceDefaultPrimarySoftwaresItem {
  /**
   * software field in *Credits → Default → Primary → Softwares*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.softwares[].software
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  software: prismic.KeyTextField;
}

/**
 * Item in *Credits → Default → Primary → Skills*
 */
export interface CreditsSliceDefaultPrimarySkillsItem {
  /**
   * skill field in *Credits → Default → Primary → Skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.skills[].skill
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skill: prismic.KeyTextField;
}

/**
 * Item in *Credits → Default → Primary → link*
 */
export interface CreditsSliceDefaultPrimaryLinkItem {
  /**
   * title field in *Credits → Default → Primary → link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.link[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * link field in *Credits → Default → Primary → link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Credits → Default → Primary → misc*
 */
export interface CreditsSliceDefaultPrimaryMiscItem {
  /**
   * title field in *Credits → Default → Primary → misc*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.misc[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Credits → Default → Primary → misc*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.misc[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Credits → Default → Primary*
 */
export interface CreditsSliceDefaultPrimary {
  /**
   * Client field in *Credits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.client[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  client: prismic.GroupField<Simplify<CreditsSliceDefaultPrimaryClientItem>>;

  /**
   * Year field in *Credits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.year[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  year: prismic.GroupField<Simplify<CreditsSliceDefaultPrimaryYearItem>>;

  /**
   * role field in *Credits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.role[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  role: prismic.GroupField<Simplify<CreditsSliceDefaultPrimaryRoleItem>>;

  /**
   * Softwares field in *Credits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.softwares[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  softwares: prismic.GroupField<
    Simplify<CreditsSliceDefaultPrimarySoftwaresItem>
  >;

  /**
   * Skills field in *Credits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<CreditsSliceDefaultPrimarySkillsItem>>;

  /**
   * link field in *Credits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.link[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link: prismic.GroupField<Simplify<CreditsSliceDefaultPrimaryLinkItem>>;

  /**
   * misc field in *Credits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: credits.default.primary.misc[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  misc: prismic.GroupField<Simplify<CreditsSliceDefaultPrimaryMiscItem>>;
}

/**
 * Default variation for Credits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CreditsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CreditsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Credits*
 */
type CreditsSliceVariation = CreditsSliceDefault;

/**
 * Credits Shared Slice
 *
 * - **API ID**: `credits`
 * - **Description**: Credits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CreditsSlice = prismic.SharedSlice<
  "credits",
  CreditsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Name field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Category field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * imgHero field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.imghero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imghero: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *NextProject → Default → Primary*
 */
export interface NextProjectSliceDefaultPrimary {
  /**
   * nextproject field in *NextProject → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: next_project.default.primary.nextproject
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nextproject: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for NextProject Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NextProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NextProject*
 */
type NextProjectSliceVariation = NextProjectSliceDefault;

/**
 * NextProject Shared Slice
 *
 * - **API ID**: `next_project`
 * - **Description**: NextProject
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextProjectSlice = prismic.SharedSlice<
  "next_project",
  NextProjectSliceVariation
>;

/**
 * Item in *Works → Default → Primary → Works*
 */
export interface WorksSliceDefaultPrimaryWorksItem {
  /**
   * name field in *Works → Default → Primary → Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.works[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * image field in *Works → Default → Primary → Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.works[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Works → Default → Primary*
 */
export interface WorksSliceDefaultPrimary {
  /**
   * Works field in *Works → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.works[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  works: prismic.GroupField<Simplify<WorksSliceDefaultPrimaryWorksItem>>;
}

/**
 * Default variation for Works Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Works*
 */
type WorksSliceVariation = WorksSliceDefault;

/**
 * Works Shared Slice
 *
 * - **API ID**: `works`
 * - **Description**: Works
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSlice = prismic.SharedSlice<"works", WorksSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DesignDocument,
      DesignDocumentData,
      DesignDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PhotoDocument,
      PhotoDocumentData,
      PhotoDocumentDataSlicesSlice,
      VideoDocument,
      VideoDocumentData,
      VideoDocumentDataSlicesSlice,
      WebDocument,
      WebDocumentData,
      WebDocumentDataSlicesSlice,
      WorksDocument,
      WorksDocumentData,
      WorksDocumentDataSlicesSlice,
      AllDocumentTypes,
      BigImageSlice,
      BigImageSliceDefaultPrimary,
      BigImageSliceVideoPrimary,
      BigImageSliceVariation,
      BigImageSliceDefault,
      BigImageSliceVideo,
      CatchphraseSlice,
      CatchphraseSliceDefaultPrimary,
      CatchphraseSliceVariation,
      CatchphraseSliceDefault,
      ComplementSlice,
      ComplementSliceDefaultPrimary,
      ComplementSliceVideoPrimary,
      ComplementSliceVariation,
      ComplementSliceDefault,
      ComplementSliceVideo,
      CreditsSlice,
      CreditsSliceDefaultPrimaryClientItem,
      CreditsSliceDefaultPrimaryYearItem,
      CreditsSliceDefaultPrimaryRoleItem,
      CreditsSliceDefaultPrimarySoftwaresItem,
      CreditsSliceDefaultPrimarySkillsItem,
      CreditsSliceDefaultPrimaryLinkItem,
      CreditsSliceDefaultPrimaryMiscItem,
      CreditsSliceDefaultPrimary,
      CreditsSliceVariation,
      CreditsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      NextProjectSlice,
      NextProjectSliceDefaultPrimary,
      NextProjectSliceVariation,
      NextProjectSliceDefault,
      WorksSlice,
      WorksSliceDefaultPrimaryWorksItem,
      WorksSliceDefaultPrimary,
      WorksSliceVariation,
      WorksSliceDefault,
    };
  }
}
