// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  big_image: defineAsyncComponent(() => import("./BigImage/index.vue")),
  catchphrase: defineAsyncComponent(() => import("./Catchphrase/index.vue")),
  complement: defineAsyncComponent(() => import("./Complement/index.vue")),
  credits: defineAsyncComponent(() => import("./Credits/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  name: defineAsyncComponent(() => import("./Name/index.vue")),
  next_project: defineAsyncComponent(() => import("./NextProject/index.vue")),
  photo: defineAsyncComponent(() => import("./Photo/index.vue")),
  video: defineAsyncComponent(() => import("./BigVideo/index.vue")),
  works: defineAsyncComponent(() => import("./Works/index.vue")),
});
